services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WHITELISTED=${WHITELISTED}
      - BLOG_URL=${BLOG_URL}
    command: node ./bin/www
    volumes:
      - /data/coolify/applications/og8gwww/files:/app/files:Z # Volume is differeint in the production env. 