[build]
packages = ["google-chrome-stable"]

[phases.setup]
commands = [
  "apt-get update",
  "apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libxss1 libxtst6 lsb-release xdg-utils wget gnupg --no-install-recommends",
  "rm -rf /var/lib/apt/lists/*",
  "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg",
  "sh -c 'echo \"deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'",
  "apt-get update",
  "apt-get install -y google-chrome-stable"
]

[env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
